In [1]:
import tensorflow as tf

The Dataset object is a Python iterable. This makes it possible to consume its elements using a for loop:

In [2]:
dataset = tf.data.Dataset.from_tensor_slices([8, 3, 0, 8, 2, 1])
dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [3]:
for elem in dataset:
  print(elem)

tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [4]:
for elem in dataset:
  print(elem.numpy())

8
3
0
8
2
1


Or by explicitly creating a Python iterator using iter and consuming its elements using next:

In [5]:
it = iter(dataset)
print(next(it).numpy())

8


In [6]:
print(next(it).numpy())

3


In [7]:
print(next(it).numpy())

0


In [8]:
dataset1 = tf.data.Dataset.from_tensor_slices(tf.random.uniform([3, 10]))
dataset1.element_spec

TensorSpec(shape=(10,), dtype=tf.float32, name=None)

In [9]:
for elem in dataset1:
  print(elem)

tf.Tensor(
[0.00404954 0.2389456  0.06523871 0.50624466 0.88319206 0.24818277
 0.9167843  0.8961861  0.72291243 0.8221998 ], shape=(10,), dtype=float32)
tf.Tensor(
[0.24850297 0.75202084 0.9261923  0.383839   0.34869385 0.27848065
 0.9692353  0.83514416 0.28471327 0.1577766 ], shape=(10,), dtype=float32)
tf.Tensor(
[0.5283096  0.19883692 0.9244007  0.97104514 0.8017665  0.1745075
 0.7995188  0.22323895 0.9560783  0.25470066], shape=(10,), dtype=float32)


In [10]:
dataset2 = tf.data.Dataset.from_tensor_slices(
   (tf.random.uniform([4]),
    tf.random.uniform([4, 100], maxval=100, dtype=tf.int32)))

dataset2.element_spec

(TensorSpec(shape=(), dtype=tf.float32, name=None),
 TensorSpec(shape=(100,), dtype=tf.int32, name=None))

In [11]:
for elem in dataset2:
  print(elem[0].numpy(),elem[1].numpy())

0.23637867 [89 13 59 67 85 19 37 60 90 75 81 14 81 98 48 95 63 55 17 19 10 98 96 50
 29 90 51 85 17 43  7 75  2  5 20 23 96 99 74 11 75 40 34 20 22 44 38  2
  3 78 18 27 65 14 29 68 74 25 85 30 77 79 97 76 61 70 93 46 56 20 81 48
 65 24 86  9 45 72 55 83 88 90 20 31 78 98 77 11 84 19 68 40 97 21 89  2
 41 54 76 24]
0.41640198 [91 72 82 52 98 61 90 15 12 58 69 72 71 54 87 23 82 35 34 77 18 19 74 95
 26 57 53 89 14  9 63 96 67 65 14 56 53  5 69 42 58  2 90  3 74 11  1 22
 53 14 96 40 60 84 59 40 28 29 86 14 30 16 54 98  7 67 13 94 94 31 20 58
  7 79 74 36 70 87 76 81 92 11 89 59 26 66 22 58 37 37 25 50 88 56 87 87
 12 85 68 69]
0.062131524 [88  6 31 36 91  8 36 21 37 73  3 16 58 45 55 77 97 18 55 60 68 85 34 57
 64 35 48 90 87 75 90 25 11 18  2 30 33 94 47 92 40 37 67 46 37 82 91 85
 71 85 22 46 76 54 47 80 54 31 28 24 97 70 89 57 93 20 89 86 65 54 11 90
 53 89 37 89 20 70 45 44 58 30 62 70 44 80 46 21 38 34 11 63 32  3 67 53
 13 39 42 89]
0.64761806 [78 68 52 99 25 63 55 76 36 62 50 28 

In [12]:
dataset3 = tf.data.Dataset.zip((dataset1, dataset2))

dataset3.element_spec

(TensorSpec(shape=(10,), dtype=tf.float32, name=None),
 (TensorSpec(shape=(), dtype=tf.float32, name=None),
  TensorSpec(shape=(100,), dtype=tf.int32, name=None)))

In [13]:
for elem in dataset3:
  print(elem[0].numpy(),elem[1])

[0.00404954 0.2389456  0.06523871 0.50624466 0.88319206 0.24818277
 0.9167843  0.8961861  0.72291243 0.8221998 ] (<tf.Tensor: shape=(), dtype=float32, numpy=0.23637866973876953>, <tf.Tensor: shape=(100,), dtype=int32, numpy=
array([89, 13, 59, 67, 85, 19, 37, 60, 90, 75, 81, 14, 81, 98, 48, 95, 63,
       55, 17, 19, 10, 98, 96, 50, 29, 90, 51, 85, 17, 43,  7, 75,  2,  5,
       20, 23, 96, 99, 74, 11, 75, 40, 34, 20, 22, 44, 38,  2,  3, 78, 18,
       27, 65, 14, 29, 68, 74, 25, 85, 30, 77, 79, 97, 76, 61, 70, 93, 46,
       56, 20, 81, 48, 65, 24, 86,  9, 45, 72, 55, 83, 88, 90, 20, 31, 78,
       98, 77, 11, 84, 19, 68, 40, 97, 21, 89,  2, 41, 54, 76, 24],
      dtype=int32)>)
[0.24850297 0.75202084 0.9261923  0.383839   0.34869385 0.27848065
 0.9692353  0.83514416 0.28471327 0.1577766 ] (<tf.Tensor: shape=(), dtype=float32, numpy=0.4164019823074341>, <tf.Tensor: shape=(100,), dtype=int32, numpy=
array([91, 72, 82, 52, 98, 61, 90, 15, 12, 58, 69, 72, 71, 54, 87, 23, 82,
       35, 3

In [14]:
dataset4 = tf.data.Dataset.from_tensors(tf.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4]))
dataset4.element_spec

SparseTensorSpec(TensorShape([3, 4]), tf.int32)

In [15]:
train, test = tf.keras.datasets.fashion_mnist.load_data()

29515/29515 ━━━━━━━━━━━━━━━━━━━━ 0s 16us/step
26421880/26421880 ━━━━━━━━━━━━━━━━━━━━ 24s 1us/step
5148/5148 ━━━━━━━━━━━━━━━━━━━━ 0s 1us/step
4422102/4422102 ━━━━━━━━━━━━━━━━━━━━ 6s 1us/step


In [26]:
import numpy as np

In [27]:
images, labels = train
images = images/255.0
labels = labels.astype(np.int32)

In [28]:
fmnist_train_ds = tf.data.Dataset.from_tensor_slices((images, labels))
fmnist_train_ds = fmnist_train_ds.shuffle(5000).batch(32)

model = tf.keras.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(10)
])

model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

In [29]:
model.fit(fmnist_train_ds, epochs=2)

Epoch 1/2
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.7375 - loss: 0.7765
Epoch 2/2
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8400 - loss: 0.4707


In [30]:
model.fit(fmnist_train_ds.repeat(), epochs=2, steps_per_epoch=20)

Epoch 1/2
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8570 - loss: 0.4171 
Epoch 2/2
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8268 - loss: 0.5232


In [31]:
loss, accuracy = model.evaluate(fmnist_train_ds)
print("Loss :", loss)
print("Accuracy :", accuracy)

1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8475 - loss: 0.4433
Loss : 0.43952062726020813
Accuracy : 0.848716676235199


In [32]:
loss, accuracy = model.evaluate(fmnist_train_ds.repeat(), steps=10)
print("Loss :", loss)
print("Accuracy :", accuracy)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8789 - loss: 0.3948 
Loss : 0.4057239592075348
Accuracy : 0.856249988079071


In [33]:
predict_ds = tf.data.Dataset.from_tensor_slices(images).batch(32)
result = model.predict(predict_ds, steps = 10)
print(result.shape)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 
(320, 10)
